/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var fibFinder = function(value){
  var firstNum = 1; //first number
  var secondNum = 0; //second number
  var nextNum = 0; //next number in sequence
  var sum = 0; //sum of even number in fib sequence

  while(nextNum <= value){
    nextNum = secondNum + firstNum; //add first number and second number to get next number in fibonacci sequence - starts with 1
    if(nextNum % 2 === 0){
      //test to see if nextNum is even. If so add to sum variable
      sum += nextNum;
    }
    //increment the sequence
    secondNum = firstNum //assign first number to second number variable
    firstNum = nextNum; //assign the next number to first number variable
  }

  return sum;
};

console.log(fibFinder(4000000))
